// Central icon set (lucide-react). Monochrome SVGs that inherit `currentColor`,
// so they theme automatically (light/dark). Import from here — not lucide
// directly — so the app's icon vocabulary stays consistent and swappable.
export {
  // chrome / navigation
  LayoutDashboard,
  GitPullRequest,
  Workflow,
  Settings,
  ShieldCheck,
  Search,
  Menu,
  Bell,
  Sun,
  Moon,
  Monitor,
  LogOut,
  // PR sub-tabs / buckets
  LayoutList,
  GitPullRequestArrow,
  Eye,
  Users,
  UserCheck,
  UserPlus,
  GitBranch,
  Trash2,
  RotateCcw,
  FilePenLine,
  // pipelines
  Play,
  History,
  LineChart,
  Activity,
  Dices,
  // work items
  ClipboardList,
  ListTodo,
  CalendarClock,
  ListFilter,
  Bug,
  Link2,
  SquarePen,
  Layers,
  Flag,
  CircleUser,
  SlidersHorizontal,
  // content / status
  MessageSquare,
  Inbox,
  CheckCircle2,
  XCircle,
  Check,
  Info,
  Tag,
  Download,
  Printer,
  Clock,
  FolderGit2,
  Lock,
  Zap,
  GitMerge,
  GitPullRequestClosed,
  RefreshCw,
  Save,
  TriangleAlert,
  ExternalLink,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  X,
  Star,
  Plus,
  Sparkles,
  PartyPopper,
  // chevrons / paging
  ChevronRight,
  ChevronDown,
  ChevronLeft,
  ChevronsLeft,
  ChevronsRight,
  // run/build status glyphs
  Hourglass,
  Ban,
  CircleDashed,
  CircleDot,
  LoaderCircle,
  Minus,
  // onboarding tour
  Compass,
  Rocket,
  // planning
  Target,
  Calendar,
  AlertCircle,
  ArrowRight,
  Edit3,
  Send,
} from 'lucide-react';
